### ISSUE TITLE
feat: create typography components

### ISSUE THREAD

**Issue by riteshsp2000** [TEDxNITRourkela/website-v2#1]
**Is your feature request related to a problem? Please describe.**
In order to maintain consistency throughout the website, a certain number of Typography elements must be created.

**Describe the solution you'd like**
Under the `components/shared/typography` directory, create the following list of Typographies
- Headings: Heading1, Heading2, Heading3
- Paras: Body1, Body2

**Additional Context**
Checkout a similar setup [here](https://github.com/dscnitrourkela/project-oregano/tree/main/src/components/shared/Typography).

- Make sure to use ONLY `rem` as the units for typography.
- All the font properties such as weight, line height, character space, style, family must be specified.

**Comment by iamakl** [comment]
have created the file and now will add the code in it. I am taking reference from project oregano regarding the text size and fonts.

**Comment by sambit-sankalp** [comment]
Hey @iamakl, don't send an empty pull request just complete it and send the pr after that.

**Comment by iamakl** [comment]
okay @sambit-sankalp.
