### ISSUE TITLE
feat: create banner components

### ISSUE THREAD

**Issue by riteshsp2000** [TEDxNITRourkela/website-v2#4]
**Is your feature request related to a problem? Please describe.**
A horizontal banner is frequently used throughout the project with a few minor tweaks.

<img width="524" alt="Screenshot 2021-11-02 at 10 05 56 PM" src="https://user-images.githubusercontent.com/56112399/139907303-bb22aa0f-bd59-4110-9310-2924b1437ea7.png">

As seen in the above image, the first two are similar just flipped. The third one doesn't have an image, instead, it has a banner title.

**Describe the solution you'd like**
A common component can be created for the above-mentioned things with a flip prop for flipping the banner. The final implementation can be done as required.

**Additional context**
Make sure that the text-align is also flipped for the flip version.

**Comment by riteshsp2000** [comment]
@Harshavardhan7678 what's the status of this?

**Comment by Harshavardhan7678** [comment]
> @Harshavardhan7678 what's the status of this?

I faced few issues with updating the styled components but solved them over last night.
Currently, solving few errors in second column and will move ahead to complete the banner.
