### ISSUE TITLE
feat: create accordion component

### ISSUE THREAD

**Issue by riteshsp2000** [TEDxNITRourkela/website-v2#5]
**Is your feature request related to a problem? Please describe.**
Accordions as of now are only used for the general FAQ. Create a customizable component that takes in an array of objects as input and renders the accordion.

**Additional context**
- Make sure that the component is responsive
- Also, minor animations of flowing down and flowing up would be great. (No need for external libraries for such a small thing. Can be easily achieved with transitions component)
- Before creating one, lookout for some examples on the net.

**Comment by sambit-sankalp** [comment]
Can I work on this issue?
