### ISSUE TITLE
feat: create teams component

### ISSUE THREAD

**Issue by riteshsp2000** [TEDxNITRourkela/website-v2#6]
**Is your feature request related to a problem? Please describe.**
As per the designs, this component composes of 2 separate smaller components - the EB section and the team section.

**Describe the solution you'd like**
A stage-based approach is the best way for the implementation. Check out the current site code for the exact same implementation.

**Additional context**
- As with other components, the component should take in a prop of data (structure can be decided as per the implementation) which is used to render all the content.
- In the current site, the changes are abrupt and hence small animations could be the better way to go.

**Comment by Sonakshi1901** [comment]
Interested
